version: '2'
services:
    activiti-app:
        image: activiti
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://activiti-mysql:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    activiti-mysql:
        extends:
            file: mysql.yml
            service: activiti-mysql
